[patch]
title = "BN6 Random Battle"
authors = [
    "luckytyphlosion <10688458+luckytyphlosion@users.noreply.github.com>",
    "ssbmars <46971717+ssbmars@users.noreply.github.com>"
]
source = "https://github.com/luckytyphlosion/bn6-eurandom-dx"
license = "MIT"

[versions.'0.0.1']
netplay_compatibility = "bn6random"

[versions.'0.0.2']
netplay_compatibility = "bn6random_v0.0.2"

[versions.'0.0.3']
netplay_compatibility = "bn6random_v0.0.3"

[versions.'0.0.4']
netplay_compatibility = "bn6random_v0.0.4"

[versions.'0.0.5']
netplay_compatibility = "bn6random_v0.0.5"

[versions.'0.0.6']
netplay_compatibility = "bn6random_v0.0.6"
