[patch]
title = "BingusBN6"
authors = ["ssbmars <46971717+ssbmars@users.noreply.github.com>"]
source = "https://github.com/ssbmars/BBN6"
license = "MIT"

[versions.'0.0.1']
netplay_compatibility = "bingusbn6v0"
[versions.'1.0.0']
netplay_compatibility = "bingusbn6v1"
