[patch]
title = "リアルバトルネットワークゲームプレイ"
authors = ["Greiga Master <griegamaster@gmail.com>"]
source = "https://forums.therockmanexezone.com/rockman-exe-4-5-real-battle-network-gameplay-patch-t5461.html"

[versions.'0.6.0']
netplay_compatibility = "exe45realbngameplay"
