[patch]
title = "BN3 PortuguÃªs Brasileiro"
authors = ["Sahgo"]
source = "https://www.romhacking.net.br/index.php?topic=3049.0"

[versions.'1.2.0']
netplay_compatibility = "bn3"

[versions.'1.2.1']
netplay_compatibility = "bn3"
