[patch]
title = "BBBN3"
authors = ["ssbmars <46971717+ssbmars@users.noreply.github.com>"]
source = "https://github.com/ssbmars/BBN3"

[versions.'0.0.1']
netplay_compatibility = "bbn3_0"
[versions.'0.0.2']
netplay_compatibility = "bbn3_0"
