[patch]
title = "LDR Patch"
authors = ["LDR100"]

source = "https://drive.google.com/drive/folders/17M6CSQt8WcYeJbR0HprAUYgXIRwk4ePH"

[versions.'1.4.8']
netplay_compatibility = "bn6_ldrv48"
[versions.'1.4.9']
netplay_compatibility = "bn6_ldrv49"
[versions.'1.5.0']
netplay_compatibility = "bn6_ldrv50"