[patch]
title = "Mega Man Battle Network 4.5: Real Operation (US) v1.1 Real Battle Network Gameplay"
authors = ["The Rockman EXE Zone", "Greiga Master <griegamaster@gmail.com>"]
source = "https://forums.therockmanexezone.com/rockman-exe-4-5-real-battle-network-gameplay-patch-t5461.html"

[versions.'0.6.0']
netplay_compatibility = "bn45realgameplay"
